name: Release main.tex zip and PDF

on:
  push:
    tags:
      - 'v*'   # Only trigger on tag push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare release directory
        run: |
          mkdir release
          cp main.tex release/

      - name: Create zip archive
        run: |
          cd release
          zip main_tex_only.zip main.tex

      - name: Compile main.pdf
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra texlive-lang-chinese
          xelatex -interaction=nonstopmode main.tex

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/main_tex_only.zip
            src/main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}